# Generated by Django 4.1.6 on 2023-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='review',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='review',
            name='contact',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='theme',
            field=models.CharField(default='', max_length=30),
        ),
    ]
