# Generated by Django 4.1.6 on 2023-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('social_net', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='shop_images')),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
