# Generated by Django 4.1.6 on 2023-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
