# Generated by Django 4.1.6 on 2023-04-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_shop_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
