# Generated by Django 4.1.6 on 2023-04-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='google_link',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
