# Generated by Django 4.1.6 on 2023-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
