# Generated by Django 4.1.6 on 2023-04-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_post', '0003_pets_address_pets_age_pets_contact_pets_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_categories', to='pets_post.category'),
        ),
    ]
