# Generated by Django 4.1.6 on 2023-04-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_post', '0004_alter_pets_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_post.category'),
        ),
    ]
